version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: holyfatigue
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  fintrack-webapi:
    build: .
    container_name: fintrack-webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fintrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: holyfatigue
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus