spring.application.name=fintrack_webapi

# ===============================
# DATABASE LOCAL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fintrack
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================
jwt.secret=YzJmZjYyZjM0ZTRjYzQ1ZmE2OTc4YWJjZGVmMTIzNDU2Nzg5MDEyMzQ1Ng==

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# RABBITMQ LOCAL
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================
# JSON / DEBUG
# ===============================
spring.jackson.serialization.indent-output=true
logging.level.org.springframework.amqp=INFO