spring.application.name=fintrack_webapi

# ===============================
# DATABASE RENDER
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# SERVER
# ===============================
server.port=${PORT}

# ===============================
# RABBITMQ
# ===============================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.listener.simple.default-requeue-rejected=false

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.amqp=INFO
logging.level.org.springframework.rabbit=INFO

# ===============================
# REDIS
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true