spring.application.name=fintrack_webapi

# Load local .env file automatically when present
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:fintrack-local-secret-2026}

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# RABBITMQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.default-requeue-rejected=false

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG

# ===============================
# REDIS
# ===============================

spring.data.redis.host=localhost
spring.data.redis.port=6379