apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-reportes

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker-reportes

  template:
    metadata:
      labels:
        app: worker-reportes

    spec:
      containers:
      - name: worker-reportes
        image: worker-reportes:latest

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8086

        env:
        - name: RABBIT_HOST
          value: "host.docker.internal"

        - name: REDIS_HOST
          value: "host.docker.internal"